language: node_js
addons:
  chrome: stable
env:
  matrix:
    - TEST_SUITE=build
    - TEST_SUITE=unit
node_js:
  - 10
  - stable
cache:
  directories:
  - node_modules
before_install:
- cp ./src/environments/environment.example.ts ./src/environments/environment.prod.ts
- cp ./src/environments/environment.example.ts ./src/environments/environment.ts
after_install:
- npm run postinstall
script:
- npm run test:$TEST_SUITE
after_success:
- ng build --prod --aot --base-href /ngHeartFit/
- cp ./dist/fitclient/index.html ./dist/fitclient/404.html
- npm install coveralls && cat ./coverage/lcov.info | coveralls
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: dist/fitclient
  on:
    branch: master